<a href="https://colab.research.google.com/github/sheCodesAI/pytorch/blob/main/pytorch_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

torch.cuda.is_available()

True

In [2]:
torch.cuda.device_count()

1

In [3]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [4]:
torch.cuda.device(0)

##Tensors

In [5]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
tensor = torch.Tensor([[1,2,3], [4,5,6]])
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
arr * 5  # numpy

array([[ 5, 10, 15],
       [20, 25, 30]])

In [8]:
tensor * 5

tensor([[ 5., 10., 15.],
        [20., 25., 30.]])

In [9]:
arr.sum()

np.int64(21)

In [10]:
tensor.sum()

tensor(21.)

In [11]:
tensor = torch.from_numpy(arr)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [14]:
np.random.random((2,4))

array([[0.02558637, 0.9493029 , 0.61031616, 0.07164814],
       [0.95841679, 0.93849136, 0.34299174, 0.92696958]])

In [15]:
torch.rand((2,4))

tensor([[0.1158, 0.8205, 0.0802, 0.2850],
        [0.5568, 0.1000, 0.5744, 0.6242]])

In [16]:
arr.shape

(2, 3)

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr.size

6

In [19]:
arr.device

'cpu'

In [20]:
tensor.device

device(type='cpu')

##arr.to_device('cuda')
bcz numpy doesn't support gpu

In [21]:
tensor = tensor.to('cuda')

In [22]:
tensor.device

device(type='cuda', index=0)

##convert gpu to cpu again

In [23]:
tensor.cpu().numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
tensor.device

device(type='cuda', index=0)