<a href="https://colab.research.google.com/github/sheCodesAI/pytorch/blob/main/gradients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

f = 3 * a**3 - b**2
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

Without gradients:

❌ AI cannot learn.
❌ It keeps making the same mistakes.

With gradients:

✅ AI learns from errors.
✅ Accuracy improves after every training step.
In one sentence

requires_grad=True tells PyTorch to remember the calculations so it can later figure out how to improve the AI model during training.

PyTorch is mainly used to train AI models.
PyTorch uses tensors to represent data (images, text, audio, etc.), processes that data in small batches, and updates the model after each batch until it has learned from the entire dataset.

In [5]:
f.backward(gradient = torch.tensor([1,1]))

In [6]:
print(a.grad)

tensor([36., 81.])


backward() tells PyTorch to automatically calculate derivatives (gradients) using calculus.

#Summary

a = torch.tensor(2.0, requires_grad=True)

f = a**2

Here,

f=a
2

When you run:

f.backward()

PyTorch automatically computes the derivative:

da
df
	​

=2a

Since a = 2:

2×2=4

So:

print(a.grad)

Output:

tensor(4.)

In [7]:
9 * a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [8]:
print(b.grad)

tensor([-12.,  -8.])


In [11]:
-2 * b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)